# Rustfmt configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true

# The following options require nightly Rust:
# condense_wildcard_suffixes = true
# normalize_comments = true
# wrap_comments = true
# format_code_in_doc_comments = true
# comment_width = 80
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
